 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
 cp /home/aurelienbrabant/prog/qmk/util/udev/50-qmk.rules /etc/udev/rules.d/
